{% set name = "lightgbm_ray" %}
{% set version = "0.1.9" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac47f10455c069393359a18e41b646185ce7b9a762c9c41b17bf2fbaa6b934dc

build:
  noarch: python
  number: {{ build_num }}
  script:
    - rm -rf examples
    - {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - lightgbm >=3.2.1
    - xgboost_ray >=0.1.12
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - lightgbm_ray

about:
  home: https://github.com/ray-project/lightgbm_ray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Ray backend for distributed LightGBM
  dev_url: https://github.com/ray-project/lightgbm_ray

extra:
  recipe-maintainers:
    - timkpaine
